name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  validate:
    name: Validate images
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.11.1

      - name: Run `packer init`
        id: init
        run: "packer init ./base.pkr.hcl"

      # validate base image
      - name: Validate base image
        run: packer validate -var 'gcp_project_id=${{ vars.GCP_PROJECT_ID }}' -var 'gcp_credentials_json=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' -var 'my_prefix=ckrst' base.pkr.hcl
      
      # validate nomad image
      - name: Validate base image
        run: packer validate -var 'gcp_project_id=${{ vars.GCP_PROJECT_ID }}' -var 'gcp_credentials_json=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' -var 'my_prefix=ckrst' nomad.pkr.hcl
      
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: devopsbox.pkr.hcl

  build_base:
    name: Build base image
    needs: validate
    environment: prod
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.11.1

      - name: Run `packer init`
        id: init
        run: "packer init ./base.pkr.hcl"

      # build base image
      - name: Build base image
        run: packer build -var 'gcp_project_id=${{ vars.GCP_PROJECT_ID }}' -var 'gcp_credentials_json=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' -var 'my_prefix=ckrst' -var 'docker_hub_username=${{ vars.DOCKER_HUB_USERNAME }}' -var 'docker_hub_password=${{ secrets.DOCKER_HUB_PASSWORD }}' base.pkr.hcl

  build_nomad:
    name: Build nomad image
    needs: build_base
    environment: prod
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.11.1

      - name: Run `packer init`
        id: init
        run: "packer init ./nomad.pkr.hcl"

      # build base image
      - name: Build base image
        run: packer build -var 'gcp_project_id=${{ vars.GCP_PROJECT_ID }}' -var 'gcp_credentials_json=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' -var 'my_prefix=ckrst' nomad.pkr.hcl

