name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  validate:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.11.1

      - name: Run `packer init`
        id: init
        run: "packer init ./base.pkr.hcl"

      # validate base image
      - name: Validate base image
        run: packer validate base.pkr.hcl
        env:
          -PKR_VAR_gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
          -PKR_VAR_gcp_credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
          -PKR_VAR_my_prefix: "ckrst"
      


      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: devopsbox.pkr.hcl

  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      # build artifact
      - name: Build Artifact
        uses: ckrst/packer-action@main
        with:
          command: build
          arguments: "-color=true -on-error=abort"
          target: devopsbox.pkr.hcl
        env:
          PACKER_LOG: 1